apiVersion: v1
kind: Service
metadata:
  name: conquest-lims-api-service
spec:
  type: NodePort
  selector:
    app: conquest-lims-api
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007