apiVersion: apps/v1
kind: Deployment
metadata:
  name: conquest-lims-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conquest-lims-api
  template:
    metadata:
      labels:
        app: conquest-lims-api
    spec:
      containers:
      - name: conquest-lims-api
        image: conquest-lims-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
          - name: MONGO_URI
            value: mongodb://mongo:27017/conquest-lims-db